name: Build macOS GUI App

on:
  push:
    branches:
      - build-mac

jobs:
  build-macos:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.18

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          echo "Installing requirements.txt..."
          pip install -r requirements.txt || exit 1
        timeout-minutes: 60

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build with PyInstaller (GUI mode)
        run: |
          pyinstaller --noconfirm --windowed --onefile main.py
        timeout-minutes: 15

      - name: List built files
        run: ls -al dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/main
