name: Build macOS GUI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10.18
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.18'
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build application with PyInstaller
      run: |
        pyinstaller main.py --noconfirm --windowed --onefile

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/
